### ISSUE TITLE
Backend tasks

### ISSUE THREAD

**Issue by HyeseonLee** [veno501/thought-cloud#1]
- [x] Basic database setup (@HyeseonLee )

## USER package

- [x] Basic user Login & Logout system (@HyeseonLee )
    - [x] Google social Login
    - [x] Signup/registration (with email & passward)
    - [x] Logout (from Google social Login & default Login)

- [x] User settings (get user data) (@njhw20 )
    - [x] GET user data for current user
    - [x] POST/change user data for current user (password, email, theme)
    - <img src="https://user-images.githubusercontent.com/46919444/113510694-ff8d1080-9596-11eb-88a0-31d630b4d76b.png" width="150px" />

## DIARY package

- [x] Geolocation feature (@veno501 )
    - [x] Fetch location data
    - [x] Save location data to the Entry database model

- [ ] Diary entry creation pages
    - [x] Step1) Save the entry’s current date & location(@njhw20 )
    - <img src="https://user-images.githubusercontent.com/46919444/113510703-061b8800-9597-11eb-9bda-1fdf3e1e9243.png" width="150px" />

    - [ ] Step2) Select the entry’s mood (SKIPPING THIS FOR NOW)
    - <img src="https://user-images.githubusercontent.com/46919444/113510707-0a47a580-9597-11eb-9031-cb445319ef0e.png" width="150px" />

    - [ ] Step3) Entry creation system and entry details page (@Selma)
    - <img src="https://user-images.githubusercontent.com/46919444/113510712-0ddb2c80-9597-11eb-8850-abd5ba7a31f4.png" width="150px" />

    - [ ] Step4) Entry editor system (@Selma)
(Image : ??)

- [ ] Dashboard page (user dashboard/diary dashboard page for listing entries) (@Selma)
- <img src="https://user-images.githubusercontent.com/46919444/113510740-2ba89180-9597-11eb-9ac8-761f51589099.png" width="150px" />

**Comment by veno501** [comment]
Pretty much done here
